# 因子特征选取 第一版

本文档主要完成特征因子筛选, 主要是学习一下

参考论文:

- [A股上市公司财务造假预测模型研究_陶能发](C:\Users\Pomelo\Desktop\Taidi_2021\论文\A股上市公司财务造假预测模型研究_陶能发.caj)
- [中国上市公司财务造假预测模型](C:\Users\Pomelo\Desktop\Taidi_2021\论文\中国上市公司财务造假预测模型.pdf)
- etc. 看一个写一个吧


## 导入库
- pandas, numpy

In [1]:
import pandas as pd
import numpy as np

## 导入数据

- 附件一

In [2]:
raw_data1 = pd.read_excel("../附件1.xlsx")
raw_data1

           股票代码              所属行业
0        4019.0               制造业
1        4213.0               制造业
2        8166.0               制造业
3        9063.0            批发和零售业
4       10083.0   信息传输、软件和信息技术服务业
...         ...               ...
4158  4993201.0               制造业
4159  4993297.0  电力、热力、燃气及水生产和供应业
4160  4997833.0        科学研究和技术服务业
4161  4998808.0               制造业
4162  4999709.0               制造业

[4163 rows x 2 columns]

- 附件二

In [3]:
raw_data2 = pd.read_csv("../附件2.csv")
raw_data2

,TICKER_SYMBOL,ACT_PUBTIME,PUBLISH_DATE,END_DATE_REP,END_DATE,REPORT_TYPE,FISCAL_PERIOD,MERGED_FLAG,ACCOUTING_STANDARDS,CURRENCY_CD,...,CA_TURNOVER,OPER_CYCLE,INVEN_TURNOVER,FA_TURNOVER,TFA_TURNOVER,DAYS_AP,DAYS_INVEN,TA_TURNOVER,AR_TURNOVER,FLAG
0,4019,3,3,2,1,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,8166,3,3,2,1,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,9063,3,3,2,1,A,12,1,CHAS_2007,CNY,...,1.3751,148.8938,7.4240,20.9362,15.2980,75.4337,48.4911,1.2774,3.5856,0.0
3,10083,4,4,4,1,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,11737,3,3,2,1,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22208,4993201,7,7,7,6,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22209,4993297,7,7,7,6,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22210,4997833,7,7,7,6,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22211,4998808,7,7,7,6,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22212,4999709,7,7,7,6,A,12,1,CHAS_2007,CNY,...,2.6656,23.0840,21.9179,0.6571,0.6256,33.6589,16.4249,0.3692,54.0618,NaN

- 附件三

In [5]:
raw_data3 = pd.read_excel("../附件3.xlsx")
raw_data3

---

## 原始数据展示 and 操作部分

In [ ]:
raw_data1.groupby(by="所属行业").count()

In [13]:
raw_data2

,TICKER_SYMBOL,ACT_PUBTIME,PUBLISH_DATE,END_DATE_REP,END_DATE,REPORT_TYPE,FISCAL_PERIOD,MERGED_FLAG,ACCOUTING_STANDARDS,CURRENCY_CD,...,CA_TURNOVER,OPER_CYCLE,INVEN_TURNOVER,FA_TURNOVER,TFA_TURNOVER,DAYS_AP,DAYS_INVEN,TA_TURNOVER,AR_TURNOVER,FLAG
0,4019,3,3,2,1,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,8166,3,3,2,1,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,9063,3,3,2,1,A,12,1,CHAS_2007,CNY,...,1.3751,148.8938,7.4240,20.9362,15.2980,75.4337,48.4911,1.2774,3.5856,0.0
3,10083,4,4,4,1,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,11737,3,3,2,1,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22208,4993201,7,7,7,6,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22209,4993297,7,7,7,6,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22210,4997833,7,7,7,6,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22211,4998808,7,7,7,6,A,12,1,CHAS_2007,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22212,4999709,7,7,7,6,A,12,1,CHAS_2007,CNY,...,2.6656,23.0840,21.9179,0.6571,0.6256,33.6589,16.4249,0.3692,54.0618,NaN

In [9]:
# raw_data3
lst = raw_data3["含义"].tolist()
lst

['股票代码',
 '实际披露时间',
 '发布时间',
 '报告截止日期',
 '截止日期',
 '报告类型',
 '会计区间',
 '合并标志：1-合并，2-母公司',
 '会计准则',
 '货币代码',
 '货币资金',
 '结算备付金',
 '拆出资金',
 '交易性金融资产',
 '应收票据',
 '应收账款',
 '预付款项',
 '应收保费',
 '应收分保账款',
 '应收分保合同准备金',
 '应收利息',
 '应收股利',
 '其他应收款',
 '买入返售金融资产',
 '存货',
 '一年内到期的非流动资产',
 '其他流动资产',
 '流动资产合计',
 '发放委托贷款及垫款',
 '可供出售金融资产',
 '持有至到期投资',
 '长期应收款',
 '长期股权投资',
 '投资性房地产',
 '固定资产',
 '在建工程',
 '工程物资',
 '固定资产清理',
 '生产性生物资产',
 '油气资产',
 '无形资产',
 '研发支出',
 '商誉',
 '长期待摊费用',
 '递延所得税资产',
 '其他非流动资产',
 '非流动资产合计',
 '资产总计',
 '短期借款',
 '向中央银行借款',
 '吸收存款',
 '拆入资金',
 '交易性金融负债',
 '应付票据',
 '应付账款',
 '预收款项',
 '卖出回购金融资产款',
 '应付手续费及佣金',
 '应付职工薪酬',
 '应交税费',
 '应付利息',
 '应付股利',
 '其他应付款',
 '应付分保账款',
 '保险合同准备金',
 '代理买卖证券款',
 '代理承销证券款',
 '一年内到期的非流动负债',
 '预提费用',
 '其他流动负债',
 '流动负债合计',
 '长期借款',
 '应付债券',
 '长期应付款',
 '专项应付款',
 '预计负债',
 '递延收益',
 '递延所得税负债',
 '其他非流动负债',
 '非流动负债合计',
 '负债合计',
 '实收资本(或股本)',
 '资本公积',
 '减:库存股',
 '专项储备',
 '盈余公积',
 '一般风险准备',
 '未分配利润',
 '外币报表折算差额',
 '归属于母公司所有者权益合计',
 '少数股东权益',
 '所有者权益(或股东权益)合计',
 '负债和所有者权益(或股东权益)总计',
 '其他综合收益',
 '其他权益工具',
 '优先股',
 '永续债',
 '其中：优先股',
 '永续债',
 '支付其他与筹资活动有关的现金',
 '向中央银行借款净增加额',
 '存放中央银行和同业款项净增加额',
 '投资活动产生的现金流量净额',
 '取得借款收到的现金',
 '客户贷款及垫款净增加额',
 '经营活动产生的现金流量净额',
 '回购业务资金净增加额',
 '吸收投资收到的现金',
 '投资支付的现金',
 '收到其他与筹资活动有关的现金',
 '质押贷款净增加额',
 '支付保单红利的现金',
 '支付其他与投资活动有关的现金',
 '投资活动现金流入小计',
 '购买商品、接受劳务支付的现金',
 '支付其他与经营活动有关的现金',
 '收回投资收到的现金',
 '销售商品、提供劳务收到的现金',
 '收到的税费返还',
 '经营活动现金流入小计',
 '向其他金融机构拆入资金净增加额',
 '取得投资收益收到的现金',
 '取得子公司及其他营业单位支付的现金净额',
 '现金及现金等价物净增加额',
 '其中:子公司吸收少数股东投资收到的现金',
 '汇率变动对现金及现金等价物的影响',
 '支付的各项税费',
 '支付利息、手续费及佣金的现金',
 '收到再保险业务现金净额',
 '分配股利、利润或偿付利息支付的现金',
 '收到其他与投资活动有关的现金',
 '拆入资金净增加额',
 '经营活动现金流出小计',
 '收到其他与经营活动有关的现金',
 '投资活动现金流出小计',
 '客户存款和同业存放款项净增加额',
 '发行债券收到的现金',
 '保户储金及投资款净增加额',
 '支付原保险合同赔付款项的现金',
 '偿还债务支付的现金',
 '处置固定资产、无形资产和其他长期资产收回的现金净额',
 '筹资活动产生的现金流量净额',
 '加:期初现金及现金等价物余额',
 '期末现金及现金等价物余额',
 '其中:子公司支付给少数股东的股利、利润',
 '购建固定资产、无形资产和其他长期资产支付的现金',
 '筹资活动现金流入小计',
 '收取利息、手续费及佣金的现金',
 '支付给职工以及为职工支付的现金',
 '筹资活动现金流出小计',
 '处置交易性金融资产净增加额',
 '处置子公司及其他营业单位收到的现金净额',
 '收到原保险合同保费取得的现金',
 '管理费用',
 '稀释每股收益',
 '其中:对联营企业和合营企业的投资收益',
 '营业收入',
 '赔付支出净额',
 '终止经营净利润',
 '营业总收入',
 '利润总额(亏损总额以“－”号填列)',
 '非流动资产处置损失',
 '基本每股收益',
 '营业利润(亏损以“－”号填列)',
 '资产减值损失',
 '归属于母公司所有者(或股东)的综合收益总额',
 '其他综合收益',
 '保单红利支出',
 '综合收益总额',
 '利息收入',
 '归属于母公司所有者(或股东)的净利润',
 '退保金',
 '其他收益',
 '已赚保费',
 '投资收益(损失以“－”号填列)',
 '资产处置收益',
 '手续费及佣金支出',
 '财务费用',
 '公允价值变动收益(损失以“－”号填列)',
 '利息支出',
 '销售费用',
 '营业成本',
 '净利润(净亏损以“－”号填列)',
 '分保费用',
 '营业税金及附加',
 '营业外支出',
 '提取保险合同准备金净额',
 '持续经营净利润',
 '归属于少数股东的综合收益总额',
 '汇兑收益(损失以“-”号填列)',
 '所得税费用',
 '营业外收入',
 '少数股东损益',
 '手续费及佣金收入',
 '营业总成本',
 '息税前利润',
 '企业自由现金流量',
 '息前税后利润',
 '无息流动负债',
 '无息非流动负债',
 '营运资本',
 '净营运资本',
 '经营活动净收益',
 '带息流动负债',
 '扣除非经常性损益后的归属于上市公司股东的净利润',
 '息税折旧摊销前利润',
 '有形净资产',
 '净债务',
 '留存收益',
 '折旧与摊销',
 '价值变动净收益',
 '带息债务',
 '净利息费用',
 '投入资本',
 '股权自由现金流量',
 '固定资产合计',
 '非经常性损益',
 '毛利',
 '投资支出/折旧和摊销',
 '经营活动产生的现金流量净额/营业收入',
 '投资活动产生的现金流量净额占比',
 '销售商品提供劳务收到的现金/营业收入',
 '经营活动产生的现金流量净额/经营活动净收益',
 '经营活动产生的现金流量净额/营业总收入',
 '经营活动产生的现金流量净额/营业利润',
 '筹资活动产生的现金流量净额占比',
 '全部资产现金回收率',
 '应收账款/营业收入',
 '预收款项/营业收入',
 '经营活动产生的现金流量净额占比',
 '营业收入同比增长',
 '每股净资产相对年初增长',
 '总资产相对年初增长',
 '归属于母公司净利润同比增长',
 '稀释每股收益同比增长',
 '营业总额同比增长',
 '净利润同比增长',
 '营业总收入同比增长',
 '基本每股收益同比增长',
 '经营活动产生的现金流量净额同比增长',
 '归属于母公司净利润（扣除）同比增长',
 '净资产收益率（摊薄）同比增长',
 '归属于母公司的股东权益相对年初增长',
 '营业利润同比增长',
 '净资产相对年初增长',
 '每股经营活动产生的现金流量净额同比增长',
 '息税折旧摊销前利润/带息债务',
 '货币资金/流动负债',
 '现金流量利息保障倍数',
 '资产负债率',
 '经营活动现金流量净额/负债合计',
 '非筹资性现金流量净额/流动负债',
 '归属于母公司的股东权益/负债合计',
 '息税折旧摊销前利润/负债合计',
 'ebitda利息保障倍数',
 '保守速动比率',
 '产权比率',
 '经营活动现金流量净额/净债务',
 '非筹资性现金流量净额/负债总额',
 '负债合计/归属于母公司的股东权益',
 '有形净资产/带息债务',
 '货币资金/带息流动负债',
 '经营活动现金流量净额/带息债务',
 '速动比率',
 '非流动负债与营运资金比率',
 'ebit利息保障倍数',
 '营业利润/负债合计',
 '经营活动现金流量净额/流动负债',
 '有形净资产/净债务',
 '流动比率',
 '有形净资产/负债合计',
 '经营活动现金流量净额/非流动负债',
 '归属于母公司的股东权益/带息债务',
 '营业利润/流动负债',
 '每股收益(期末摊薄)',
 '每股股东自由现金流量',
 '每股留存收益',
 '每股经营活动产生的现金流量净额',
 '每股公积金',
 '每股息税前利润',
 '每股净资产',
 '每股未分配利润',
 '每股营业利润',
 '每股营业收入',
 '每股现金流量净额',
 '每股盈余公积',
 '每股营业总收入',
 '每股企业自由现金流量',
 '每股资本公积',
 '总资产净利率',
 '销售净利润率',
 '净资产收益率',
 '净资产收益率(加权平均)',
 '总资产报酬率',
 '净资产收益率(扣除摊薄)',
 '净资产收益率(摊薄)',
 '销售毛利率',
 '投入资本回报率',
 '净资产收益率(平均)',
 '所有者权益/总资产',
 '货币资金/总资产',
 '应付债券/总资产',
 '归属于母公司的股东权益/投入资本',
 '长期待摊费用/总资产',
 '非流动资产/总资产',
 '短期借款/总资产',
 '非流动负债/负债合计',
 '权益乘数',
 '资本固定化比率',
 '有形净资产/总资产',
 '长期借款/总资产',
 '预付账款/总资产',
 '带息债务/投入资本',
 '应付账款/总资产',
 '存货/总资产',
 '流动负债/负债合计',
 '预收款项/总资产',
 '应收账款/总资产',
 '归属于母公司的股东权益/总资产',
 '固定资产合计/总资产',
 '固定资产/总资产',
 '留存收益/总资产',
 '流动资产/总资产',
 '无形资产/总资产',
 '资产减值损失 /营业总收入',
 '价值变动净收益/营业总收入',
 '营业成本/营业总收入',
 '销售费用/营业总收入',
 '期间费用/营业总收入',
 '投资收益/营业总收入',
 '所得税/利润总额',
 '经营活动净收益/利润总额',
 '营业利润/营业总收入',
 '财务费用/营业总收入',
 '价值变动净收益/利润总额',
 '扣除非经常损益后的归母净利润/归母净利润',
 '经营活动净收益/营业总收入',
 '营业外收支净额/利润总额',
 '营业收入/营业总收入',
 '营业外收入/营业总收入',
 '净利润/营业总收入',
 '营业总成本/营业总收入',
 '公允价值变动收益/营业总收入',
 '利润总额/营业总收入',
 '营业外支出/营业总收入',
 '管理费用/营业总收入',
 'ebitda/营业总收入',
 '营业税金及附加/营业总收入',
 '所得税/营业总收入',
 'ebit/营业总收入',
 '营业利润/利润总额',
 '应收账款周转天数',
 '应付账款周转率',
 '流动资产周转率',
 '营业周期',
 '存货周转率',
 '固定资产周转率',
 '固定资产合计周转率',
 '应付账款周转天数',
 '存货周转天数',
 '总资产周转率',
 '应收账款周转率',
 '是否在当年造假']

---

## 特征因子寻找

### Mscore模型中所使用的因子

1. 应收账款指数

- 计算方式: 本期应收账款占营业收入的百分比 / 上期应收账款占营业收入的百分比
- 因子: 
    - `ADV_R_R` 预收账款/营业收入
    - `AR_R` 应收账款/营业收入

In [34]:
def showCount(data, name):
    temp = data[name]
    print("{} 非空数值数:{}".format(name, temp.count()))
    return temp

In [14]:
adv_r_r = raw_data2["ADV_R_R"]
print("ADV_R_R非空数值数:",adv_r_r.count())
ar_r = raw_data2["AR_R"]
print("AR_R非空数值数:",ar_r.count())

ADV_R_R非空数值数: 6724
AR_R非空数值数: 6451

2. 毛利率指数
- 计算方式: 上期毛利率/本期毛利率
- 因子:
    - `GROSS_MARGIN` 销售毛利率

In [15]:
gross_margin = raw_data2["GROSS_MARGIN"]
print("GROSS_MARGIN非空数值数:",gross_margin.count())

GROSS_MARGIN非空数值数: 7191

3. 资产质量指数
- 计算方式: 本期非实物资产比例/上期非实物资产比例
- 因子:
    - `INTAN_A_TA` 无形资产/总资产
    - ...不只是包含无形资产, 集中在表B300-B325区域

In [16]:
intan_a_ta = raw_data2["INTAN_A_TA"]
print("INTAN_A_TA非空数值数:", intan_a_ta.count())

INTAN_A_TA非空数值数: 6933

4. 营业收入指数

- 计算方式: 本期营业收入/上期营业收入
- 因子:
    - `REVENUE` 营业收入
    - `REVENUE_YOY` 营业收入同比增长

In [20]:
revenue = raw_data2["REVENUE"]
revenue_yoy = raw_data2["REVENUE_YOY"]
print("REVENUE非空数值数:",revenue.count())
print("REVENUE_YOY非空数值数:",revenue_yoy.count())

REVENUE非空数值数: 22209
REVENUE_YOY非空数值数: 7122

5. 折旧率指数
- 计算方式: 上期折旧率/本期折旧率. 折旧率 = 折旧费用/固定资产原值
- 因子:
    - `DA` 折旧与摊销
    - `FIXED_ASSETS` 固定资产

In [23]:
da = raw_data2["DA"]
fixed_assets = raw_data2["FIXED_ASSETS"]
print("DA非空数值数:",da.count())
print("FIXED_ASSETS非空数值数:",fixed_assets.count())

DA非空数值数: 6305
FIXED_ASSETS非空数值数: 22208

6. 销售管理费用指数
- 计算方式: 本期销售管理费用占营业收入比例/上期销售管理费用占营业收入比例
- 因子:
    - `C_FR_SALE_G_S` 销售商品、提供劳务收到的现金
    - `CFSGS_R` 销售商品提供劳务收到的现金/营业收入
    - `SELL_EXP` 销售费用
    - 营业收入见`4`

In [27]:
c_fr_sale_g_s = raw_data2["C_FR_SALE_G_S"]
cfsgs_r = raw_data2["CFSGS_R"]
sell_exp = raw_data2["SELL_EXP"]
print("C_FR_SALE_G_S非空数值数:",c_fr_sale_g_s.count())
print("CFSGS_R非空数值数:",cfsgs_r.count())
print("SELL_EXP非空数值数:",sell_exp.count())

C_FR_SALE_G_S非空数值数: 21720
CFSGS_R非空数值数: 6891
SELL_EXP非空数值数: 21294

7. 财务杠杆指数
- 计算方式: 本期资产负债率/上期资产负债率
- 因子:
    - `ASSET_LIAB_RATIO` 资产负债率

In [28]:
asset_liab_ratio = raw_data2["ASSET_LIAB_RATIO"]
print("ASSET_LIAB_RATIO非空数值数:",asset_liab_ratio.count())

ASSET_LIAB_RATIO非空数值数: 7238

8. 总应计项
- 计算方式: 应计项/总资产
- 应计项 = (本期上期流动资产的差 - 本期上期货币资金的差) - (本期上期流动负债的差 - 本期上期一年内到期长期负债的茶 - 本期上期应交税费的差) - 折旧费用
- 因子:
    - `T_CL` 流动负债合计
    - `T_CA` 流动资产合计
    - `CASH_C_EQUIV` 货币资金
    - `NCL_WITHIN_1Y` 一年内到期的非流动负债
    - `TAXES_PAYABLE` 应交税费
    - 折旧与摊销见`4`

In [32]:
t_cl = raw_data2["T_CL"]
t_ca = raw_data2["T_CA"]
cash_c_equiv = raw_data2["CASH_C_EQUIV"]
ncl_within_1y = raw_data2["NCL_WITHIN_1Y"]
taxes_payable = raw_data2["TAXES_PAYABLE"]
print("T_CL非空数值数:",t_cl.count())
print("T_CA非空数值数:",t_ca.count())
print("CASH_C_EQUIV非空数值数:",cash_c_equiv.count())
print("NCL_WITHIN_1Y非空数值数:",ncl_within_1y.count())
print("ASSET_LIAB_RATIO非空数值数:",taxes_payable.count())

T_CL非空数值数: 21753
T_CA非空数值数: 21753
CASH_C_EQUIV非空数值数: 22212
NCL_WITHIN_1Y非空数值数: 10996
ASSET_LIAB_RATIO非空数值数: 22210

---

### Fscore模型中使用的因子

1. RSST应计项
- 计算方法: (经营资本变动值 + 非现金净营运资产变动值 + 金融资产变动值) / 平均总资产
- 因子:
    - ...

2. 应收账款变动率
- 计算方法: 应收账款变动值/平均总资产
- 因子:
    - `AR_TA` 应收账款/总资产

In [35]:
ar_ta = showCount(raw_data2, "AR_TA")

AR_TA 非空数值数:6558

3. 存货变动率
- 计算方法: 存货变动值/平均总资产
- 因子:
    - `INVEN_TA` 存货/总资产

In [36]:
inven_ta = showCount(raw_data2, "INVEN_TA")

INVEN_TA 非空数值数:6891

4. 软资产比例
- 计算方法: (总资产 - 固定资产 - 在建工程 - 工程物资 - 货币资金) / 总资产
- 因子:
    - `CIP` 在建工程
    - `CONST_MATERIALS` 工程物资
    - 货币基金见`Mscore 8`
    - 固定资产见`Mscore 5`

In [37]:
cip = showCount(raw_data2, "CIP")
const_materials = showCount(raw_data2, "CONST_MATERIALS")

CIP 非空数值数:18579
CONST_MATERIALS 非空数值数:3336

5. 现金销售率
- 计算方法: (营业收入 - 应收账款变动值) / 营业收入
- 因子:
    - 营业收入见`Mscore 4`
    - `AR` 应收账款

In [38]:
ar = showCount(raw_data2, "AR")

AR 非空数值数:21471

6. ROA增长率
- 计算方法: 第t年(净利润 / 平均总资产) -  第t-1年(净利润 / 平均总资产)
- 因子:
    - `ROA` 总资产净利率

In [39]:
roa = showCount(raw_data2, "ROA")

ROA 非空数值数:7182

7. 是否再融资
- 有股权或债券融资
- 因子:
    - `LT_EQUITY_INVEST` 长期股权投资

In [40]:
lt_equity_invest = showCount(raw_data2, "LT_EQUITY_INVEST")

LT_EQUITY_INVEST 非空数值数:13027

### 某个模型1

1. 其他应收款比例
- 计算方法: 其他应收款/总资产
- 因子: `OTH_RECEIV` 其他应收款

2. 是否亏损
- 计算方法: 扣除非经常性损益后ROE小于0为1, 否则为0
- 因子: ROE系列(见243.293.294.296.297.300)
    - `ROE_CUT` 净资产收益率(扣除摊薄) (我认为是这个)

In [41]:
oth_reveiv = showCount(raw_data2, "OTH_RECEIV")
roe_cut = showCount(raw_data2, "ROE_CUT")

OTH_RECEIV 非空数值数:20857
ROE_CUT 非空数值数:6566

---

## 数据预处理

In [105]:
raw_data_factory = pd.read_csv("../Data/制造业.csv", encoding="utf8")

- 删除空值＞50%的因子

In [162]:
[m, n] = raw_data_factory.shape
nan_col = raw_data_factory.isnull().sum()
nan_col_lst = nan_col[nan_col > m * 0.5].index.to_list()
clean_data_factory = raw_data_factory.drop(columns=nan_col_lst, axis=1)
clean_data_factory

,Unnamed: 0,TICKER_SYMBOL,ACT_PUBTIME,PUBLISH_DATE,END_DATE_REP,END_DATE,REPORT_TYPE,FISCAL_PERIOD,MERGED_FLAG,ACCOUTING_STANDARDS,...,BIZ_TAX_SURCHG,NOPERATE_EXP,GOING_CONCERN_NI,COMPR_INC_ATTR_M_S,INCOME_TAX,NOPERATE_INCOME,MINORITY_GAIN,T_COGS,FLAG,industry
0,0,4019,3,3,2,1,A,12,1,CHAS_2007,...,1505596.10,224194.93,NaN,NaN,19509143.39,16781651.83,NaN,3.885748e+08,0.0,制造业
1,1,8166,3,3,2,1,A,12,1,CHAS_2007,...,28213513.69,1071702.74,NaN,NaN,52563706.01,22480726.69,NaN,4.930772e+09,0.0,制造业
2,4,11737,3,3,2,1,A,12,1,CHAS_2007,...,8298888.47,633458.95,NaN,21722671.14,36404446.16,60365828.87,21722671.14,1.384902e+09,0.0,制造业
3,6,16479,3,3,2,1,A,12,1,CHAS_2007,...,11585500.32,1727998.62,NaN,36810.52,17533501.14,18113878.30,36810.52,2.153059e+09,0.0,制造业
4,7,16842,4,4,3,1,A,12,1,CHAS_2007,...,1621817.64,499429.33,NaN,919215.16,8519689.96,4847047.58,919215.16,3.384751e+08,0.0,制造业
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13964,22205,4990942,7,7,7,6,A,12,1,CHAS_2007,...,19976636.83,12343645.55,1.724604e+08,19860974.28,43497296.63,3451683.50,19860974.28,1.634816e+09,NaN,制造业
13965,22206,4992204,7,7,7,6,A,12,1,CHAS_2007,...,4930086.99,6463772.11,6.729722e+07,NaN,9266856.60,NaN,NaN,5.006001e+08,NaN,制造业
13966,22207,4992858,7,7,7,6,A,12,1,CHAS_2007,...,2920643.92,111091.53,6.933519e+06,1889692.56,898725.15,32321.42,1889692.56,3.113814e+08,NaN,制造业
13967,22208,4993201,7,7,7,6,A,12,1,CHAS_2007,...,18134817.61,4526795.07,9.218567e+07,-7181958.13,31889179.48,106277.29,-7181958.13,1.650710e+09,NaN,制造业
13968,22211,4998808,7,7,7,6,A,12,1,CHAS_2007,...,29732753.24,901275.67,6.794989e+07,-5187877.57,13703182.05,103999.48,-5190867.54,1.648540e+09,NaN,制造业

- 去除无用因子

In [163]:
clean_data_factory = clean_data_factory.drop(columns=["Unnamed: 0", "ACT_PUBTIME", "PUBLISH_DATE","END_DATE_REP",
                                                     "END_DATE","REPORT_TYPE","FISCAL_PERIOD","MERGED_FLAG",
                                                     "ACCOUTING_STANDARDS","CURRENCY_CD"])
clean_data_factory

,TICKER_SYMBOL,CASH_C_EQUIV,NOTES_RECEIV,AR,PREPAYMENT,OTH_RECEIV,INVENTORIES,OTH_CA,T_CA,AVAIL_FOR_SALE_FA,...,BIZ_TAX_SURCHG,NOPERATE_EXP,GOING_CONCERN_NI,COMPR_INC_ATTR_M_S,INCOME_TAX,NOPERATE_INCOME,MINORITY_GAIN,T_COGS,FLAG,industry
0,4019,6.719939e+08,1.643520e+08,3.451945e+08,1.039522e+07,3584940.60,9.372176e+07,NaN,1.291554e+09,NaN,...,1505596.10,224194.93,NaN,NaN,19509143.39,16781651.83,NaN,3.885748e+08,0.0,制造业
1,8166,1.010981e+09,2.155752e+09,2.887470e+08,1.075202e+08,85626756.05,1.049809e+09,1.080342e+07,4.709240e+09,NaN,...,28213513.69,1071702.74,NaN,NaN,52563706.01,22480726.69,NaN,4.930772e+09,0.0,制造业
2,11737,1.502023e+09,2.688988e+07,9.517806e+08,4.157376e+07,37519236.14,6.611381e+08,3.919438e+08,3.619333e+09,1500000.00,...,8298888.47,633458.95,NaN,21722671.14,36404446.16,60365828.87,21722671.14,1.384902e+09,0.0,制造业
3,16479,9.966031e+08,3.686740e+05,2.824134e+08,2.741431e+07,67249473.03,3.400061e+08,8.145214e+08,2.554056e+09,NaN,...,11585500.32,1727998.62,NaN,36810.52,17533501.14,18113878.30,36810.52,2.153059e+09,0.0,制造业
4,16842,5.763404e+07,8.990000e+06,5.941825e+07,3.603420e+07,775584.93,6.985958e+07,4.721015e+05,2.331838e+08,NaN,...,1621817.64,499429.33,NaN,919215.16,8519689.96,4847047.58,919215.16,3.384751e+08,0.0,制造业
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13964,4990942,2.576919e+08,3.315863e+08,6.357174e+08,3.247564e+07,16499824.39,5.204736e+08,1.828237e+08,1.977268e+09,1120914.00,...,19976636.83,12343645.55,1.724604e+08,19860974.28,43497296.63,3451683.50,19860974.28,1.634816e+09,NaN,制造业
13965,4992204,5.346339e+07,5.015221e+07,1.062665e+08,3.001468e+06,1910677.33,6.922770e+07,1.312207e+06,2.853342e+08,NaN,...,4930086.99,6463772.11,6.729722e+07,NaN,9266856.60,NaN,NaN,5.006001e+08,NaN,制造业
13966,4992858,2.440501e+08,3.076474e+05,8.106961e+07,3.484379e+06,4939396.20,9.927149e+07,5.539442e+06,4.502721e+08,NaN,...,2920643.92,111091.53,6.933519e+06,1889692.56,898725.15,32321.42,1889692.56,3.113814e+08,NaN,制造业
13967,4993201,1.383177e+08,2.065400e+06,2.356441e+08,2.378197e+07,10805864.85,3.880520e+08,2.597709e+07,8.246441e+08,NaN,...,18134817.61,4526795.07,9.218567e+07,-7181958.13,31889179.48,106277.29,-7181958.13,1.650710e+09,NaN,制造业
13968,4998808,1.636861e+09,1.315565e+06,6.862857e+08,5.058011e+07,NaN,1.247265e+09,4.129781e+07,3.666948e+09,49055962.21,...,29732753.24,901275.67,6.794989e+07,-5187877.57,13703182.05,103999.48,-5190867.54,1.648540e+09,NaN,制造业

- 空值率20%到50%的数据用均值填充

In [164]:
[m, n] = clean_data_factory.shape
nan_col = clean_data_factory.isnull().sum()
nan_col_lst1 = nan_col[nan_col < m*0.5].index.to_list()
nan_col_lst2 = nan_col[nan_col > m*0.2].index.to_list()
nan_col_lst = []
print(nan_col_lst2)
for i in nan_col_lst2:
    if i in nan_col_lst1:
        nan_col_lst.append(i)
for na in nan_col_lst:
    mean_val = clean_data_factory[na].mean()
    clean_data_factory[na].fillna(mean_val, inplace=True)

['AVAIL_FOR_SALE_FA', 'LT_EQUITY_INVEST', 'LT_AMOR_EXP', 'OTH_NCA', 'ST_BORR', 'NOTES_PAYABLE', 'INT_PAYABLE', 'MINORITY_INT', 'OTH_COMPRE_INCOME', 'C_PAID_OTH_FINAN_A', 'C_PAID_INVEST', 'PROC_SELL_INVEST', 'REFUND_OF_TAX', 'GAIN_INVEST', 'C_FR_OTH_INVEST_A', 'ASSETS_IMPAIR_LOSS', 'OTH_COMPR_INCOME', 'GOING_CONCERN_NI', 'COMPR_INC_ATTR_M_S', 'MINORITY_GAIN']

In [126]:
clean_data_factory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13969 entries, 0 to 13968
Data columns (total 97 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TICKER_SYMBOL        13969 non-null  int64
 1   CASH_C_EQUIV         13968 non-null  float64
 2   NOTES_RECEIV         12500 non-null  float64
 3   AR                   13795 non-null  float64
 4   PREPAYMENT           13940 non-null  float64
 5   OTH_RECEIV           13302 non-null  float64
 6   INVENTORIES          13938 non-null  float64
 7   OTH_CA               12531 non-null  float64
 8   T_CA                 13969 non-null  float64
 9   AVAIL_FOR_SALE_FA    13969 non-null  float64
 10  LT_EQUITY_INVEST     13969 non-null  float64
 11  FIXED_ASSETS         13968 non-null  float64
 12  CIP                  12763 non-null  float64
 13  INTAN_ASSETS         13885 non-null  float64
 14  LT_AMOR_EXP          10673 non-null  float64
 15  DEFER_TAX_ASSETS     13589 non-null  float64
 16  OTH_NCA              9951 non-null   float64
 17  T_NCA                13969 non-null  float64
 18  T_ASSETS             13969 non-null  float64
 19  ST_BORR              10731 non-null  float64
 20  NOTES_PAYABLE        9854 non-null   float64
 21  AP                   13812 non-null  float64
 22  ADVANCE_RECEIPTS     13758 non-null  float64
 23  PAYROLL_PAYABLE      13896 non-null  float64
 24  TAXES_PAYABLE        13967 non-null  float64
 25  INT_PAYABLE          13969 non-null  float64
 26  OTH_PAYABLE          13365 non-null  float64
 27  T_CL                 13969 non-null  float64
 28  DEFER_REVENUE        11790 non-null  float64
 29  T_NCL                13354 non-null  float64
 30  T_LIAB               13969 non-null  float64
 31  PAID_IN_CAPITAL      13964 non-null  float64
 32  CAPITAL_RESER        13850 non-null  float64
 33  SURPLUS_RESER        13852 non-null  float64
 34  RETAINED_EARNINGS    13960 non-null  float64
 35  T_EQUITY_ATTR_P      13969 non-null  float64
 36  MINORITY_INT         13969 non-null  float64
 37  T_SH_EQUITY          13969 non-null  float64
 38  T_LIAB_EQUITY        13969 non-null  float64
 39  OTH_COMPRE_INCOME    13969 non-null  float64
 40  C_PAID_OTH_FINAN_A   13969 non-null  float64
 41  N_CF_FR_INVEST_A     13964 non-null  float64
 42  C_FR_BORR            11444 non-null  float64
 43  N_CF_OPERATE_A       13968 non-null  float64
 44  C_PAID_INVEST        13969 non-null  float64
 45  C_INF_FR_INVEST_A    13542 non-null  float64
 46  C_PAID_G_S           13963 non-null  float64
 47  C_PAID_FOR_OTH_OP_A  13967 non-null  float64
 48  PROC_SELL_INVEST     13969 non-null  float64
 49  C_FR_SALE_G_S        13956 non-null  float64
 50  REFUND_OF_TAX        10702 non-null  float64
 51  C_INF_FR_OPERATE_A   13968 non-null  float64
 52  GAIN_INVEST          13969 non-null  float64
 53  N_CHANGE_IN_CASH     13968 non-null  float64
 54  FOREX_EFFECTS        11233 non-null  float64
 55  C_PAID_FOR_TAXES     13967 non-null  float64
 56  C_PAID_DIV_PROF_INT  13621 non-null  float64
 57  C_FR_OTH_INVEST_A    13969 non-null  float64
 58  C_OUTF_OPERATE_A     13968 non-null  float64
 59  C_FR_OTH_OPERATE_A   13968 non-null  float64
 60  C_OUTF_FR_INVEST_A   13956 non-null  float64
 61  C_PAID_FOR_DEBTS     11764 non-null  float64
 62  DISP_FIX_ASSETS_OTH  12377 non-null  float64
 63  N_CF_FR_FINAN_A      13843 non-null  float64
 64  N_CE_BEG_BAL         13964 non-null  float64
 65  N_CE_END_BAL         13968 non-null  float64
 66  PUR_FIX_ASSETS_OTH   13948 non-null  float64
 67  C_INF_FR_FINAN_A     12884 non-null  float64
 68  C_PAID_TO_FOR_EMPL   13968 non-null  float64
 69  C_OUTF_FR_FINAN_A    13778 non-null  float64
 70  ADMIN_EXP            13969 non-null  float64
 71  DILUTED_EPS          13231 non-null  float64
 72  REVENUE              13966 non-null  float64
 73  T_REVENUE            13966 non-null  float64
 74  T_PROFIT             13969 non-null  float64
 75  BASIC_EPS            13600 non-null  float64
 76  OPERATE_PROFIT       13969 non-null  float64
 77  ASSETS_IMPAIR_LOSS   10898 non-null  float64
 78  COMPR_INC_ATTR_P     13963 non-null  float64
 79  OTH_COMPR_INCOME     13969 non-null  float64
 80  T_COMPR_INCOME       13969 non-null  float64
 81  N_INCOME_ATTR_P      13969 non-null  float64
 82  INVEST_INCOME        11572 non-null  float64
 83  FINAN_EXP            13969 non-null  float64
 84  SELL_EXP             13941 non-null  float64
 85  COGS                 13963 non-null  float64
 86  N_INCOME             13969 non-null  float64
 87  BIZ_TAX_SURCHG       13956 non-null  float64
 88  NOPERATE_EXP         13821 non-null  float64
 89  GOING_CONCERN_NI     13969 non-null  float64
 90  COMPR_INC_ATTR_M_S   9904 non-null   float64
 91  INCOME_TAX           13838 non-null  float64
 92  NOPERATE_INCOME      13889 non-null  float64
 93  MINORITY_GAIN        9904 non-null   float64
 94  T_COGS               13969 non-null  float64
 95  FLAG                 11310 non-null  float64
 96  industry             13969 non-null  object
dtypes: float64(95), int64(1), object(1)
memory usage: 10.3+ MB

--- 
## 随机森林填补缺失值

In [165]:
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer  #填补缺失值
from sklearn.model_selection import cross_val_score

In [166]:
dtrain = clean_data_factory.drop(columns = ['FLAG','industry'],axis = 1)
dtarget = clean_data_factory['FLAG']

- 去除空值率<20%的数据按升序排序

In [167]:
sortindex = np.argsort(dtrain.isnull().sum(axis = 0)).values
#np.argsort用来排序，返回从小到大的顺序对对应的索引，然后取出其中的values
nan_coll= dtrain.isnull().sum()
a = nan_coll[nan_coll ==0 ].count()
print(a)
index = sortindex[a+1:]
print(index)

37
[59 11 53 51 43  1 68 58 55 47 24 73 72 31 41 64 78 46 85 34 60 49 87 66
 84  4  6 23 92 13 33 32 63 91 88 21  3 69 22 56 75 15 45 26 29  5 71 67
 12  7  2 62 28 61 82 42 54]

In [168]:
for i in index:
    #构造新特征矩阵和新标签
    df = dtrain
    fillc = df.iloc[:,i]
   # df = pd.concat([df.iloc[:,df.columns!=i],pd.DataFrame(y_full)],axis = 1)
    
    #在新特征矩阵中，对含有缺失值的列，进行0的填补
    df_0 = SimpleImputer(missing_values = np.nan,strategy = 'constant',fill_value = 0).fit_transform(df)
    
    #划分训练集以及测试集
    y_train = fillc[fillc.notnull()]   #不为空值的
    y_test = fillc[fillc.isnull()]     #为空值的
    x_train = df_0[y_train.index,:]
    x_test = df_0[y_test.index,:]
    
    #a
    print(y_test)
    
    #用随机森林填补缺失值
    rfc = RandomForestRegressor()
    rfc.fit(x_train,y_train)
    y_predict = rfc.predict(x_test)
    
    dtrain.iloc[y_test.index,i] = y_predict   #第六列全为空值的

71   NaN
Name: C_FR_OTH_OPERATE_A, dtype: float64
7451   NaN
Name: FIXED_ASSETS, dtype: float64
71   NaN
Name: N_CHANGE_IN_CASH, dtype: float64
71   NaN
Name: C_INF_FR_OPERATE_A, dtype: float64
71   NaN
Name: N_CF_OPERATE_A, dtype: float64
11375   NaN
Name: CASH_C_EQUIV, dtype: float64
71   NaN
Name: C_PAID_TO_FOR_EMPL, dtype: float64
71   NaN
Name: C_OUTF_OPERATE_A, dtype: float64
71      NaN
12099   NaN
Name: C_PAID_FOR_TAXES, dtype: float64
71     NaN
8305   NaN
Name: C_PAID_FOR_OTH_OP_A, dtype: float64
4729    NaN
12099   NaN
Name: TAXES_PAYABLE, dtype: float64
9063    NaN
10247   NaN
12099   NaN
Name: T_REVENUE, dtype: float64
9063    NaN
10247   NaN
12099   NaN
Name: REVENUE, dtype: float64
2128    NaN
4281    NaN
4302    NaN
6521    NaN
11375   NaN
Name: PAID_IN_CAPITAL, dtype: float64
71      NaN
4261    NaN
4963    NaN
11759   NaN
11961   NaN
Name: N_CF_FR_INVEST_A, dtype: float64
17     NaN
71     NaN
1902   NaN
3983   NaN
6209   NaN
Name: N_CE_BEG_BAL, dtype: float64
464     NaN
7873    NaN
8763    NaN
10438   NaN
11248   NaN
12838   NaN
Name: COMPR_INC_ATTR_P, dtype: float64
71      NaN
3069    NaN
5269    NaN
10247   NaN
12099   NaN
13534   NaN
Name: C_PAID_G_S, dtype: float64
5269    NaN
9063    NaN
9407    NaN
10247   NaN
12099   NaN
13534   NaN
Name: COGS, dtype: float64
57      NaN
2128    NaN
4302    NaN
9063    NaN
9271    NaN
10404   NaN
11723   NaN
11931   NaN
13064   NaN
Name: RETAINED_EARNINGS, dtype: float64
71      NaN
2500    NaN
4261    NaN
4687    NaN
4963    NaN
5079    NaN
7813    NaN
10855   NaN
11759   NaN
11782   NaN
11961   NaN
12324   NaN
13515   NaN
Name: C_OUTF_FR_INVEST_A, dtype: float64
71      NaN
142     NaN
2004    NaN
4168    NaN
4847    NaN
8277    NaN
9063    NaN
9390    NaN
12099   NaN
13044   NaN
13089   NaN
13228   NaN
13534   NaN
Name: C_FR_SALE_G_S, dtype: float64
532     NaN
774     NaN
1695    NaN
1744    NaN
1799    NaN
2766    NaN
2824    NaN
3815    NaN
4206    NaN
4435    NaN
4958    NaN
5019    NaN
12099   NaN
Name: BIZ_TAX_SURCHG, dtype: float64
71      NaN
1226    NaN
2500    NaN
4261    NaN
4687    NaN
4963    NaN
5079    NaN
7385    NaN
7813    NaN
8919    NaN
9122    NaN
10364   NaN
10620   NaN
10855   NaN
11759   NaN
11782   NaN
11961   NaN
12099   NaN
12324   NaN
12772   NaN
13515   NaN
Name: PUR_FIX_ASSETS_OTH, dtype: float64
883     NaN
1436    NaN
1587    NaN
2238    NaN
3700    NaN
4415    NaN
5269    NaN
5919    NaN
6495    NaN
6668    NaN
7581    NaN
7700    NaN
8264    NaN
8271    NaN
9063    NaN
9122    NaN
9407    NaN
10114   NaN
10247   NaN
10568   NaN
10874   NaN
11782   NaN
12067   NaN
12099   NaN
12907   NaN
13228   NaN
13410   NaN
13534   NaN
Name: SELL_EXP, dtype: float64
779     NaN
1002    NaN
1226    NaN
1587    NaN
2199    NaN
2238    NaN
2502    NaN
3069    NaN
3142    NaN
3487    NaN
4375    NaN
4415    NaN
4435    NaN
4689    NaN
5269    NaN
6079    NaN
6668    NaN
6964    NaN
7524    NaN
7551    NaN
7806    NaN
8443    NaN
9099    NaN
10371   NaN
11759   NaN
11782   NaN
11961   NaN
12099   NaN
12196   NaN
Name: PREPAYMENT, dtype: float64
316     NaN
1226    NaN
2238    NaN
3487    NaN
3725    NaN
3949    NaN
4415    NaN
4435    NaN
4689    NaN
4729    NaN
5703    NaN
5946    NaN
6668    NaN
6689    NaN
6964    NaN
7551    NaN
7806    NaN
8300    NaN
9122    NaN
9434    NaN
10371   NaN
10409   NaN
10618   NaN
10912   NaN
11759   NaN
11782   NaN
12099   NaN
12774   NaN
13280   NaN
13572   NaN
13677   NaN
Name: INVENTORIES, dtype: float64
69      NaN
79      NaN
196     NaN
495     NaN
620     NaN
         ..
10974   NaN
11671   NaN
12586   NaN
13150   NaN
13592   NaN
Name: PAYROLL_PAYABLE, Length: 73, dtype: float64
709     NaN
4295    NaN
8788    NaN
8800    NaN
8853    NaN
         ..
13440   NaN
13531   NaN
13797   NaN
13955   NaN
13965   NaN
Name: NOPERATE_INCOME, Length: 80, dtype: float64
234     NaN
433     NaN
472     NaN
612     NaN
750     NaN
         ..
13024   NaN
13122   NaN
13280   NaN
13591   NaN
13730   NaN
Name: INTAN_ASSETS, Length: 84, dtype: float64
21      NaN
57      NaN
183     NaN
493     NaN
551     NaN
         ..
13608   NaN
13652   NaN
13734   NaN
13773   NaN
13837   NaN
Name: SURPLUS_RESER, Length: 117, dtype: float64
62      NaN
293     NaN
457     NaN
504     NaN
583     NaN
         ..
12953   NaN
13212   NaN
13557   NaN
13773   NaN
13842   NaN
Name: CAPITAL_RESER, Length: 119, dtype: float64
71      NaN
308     NaN
338     NaN
457     NaN
709     NaN
         ..
13633   NaN
13677   NaN
13843   NaN
13848   NaN
13944   NaN
Name: N_CF_FR_FINAN_A, Length: 126, dtype: float64
21      NaN
77      NaN
116     NaN
357     NaN
379     NaN
         ..
13572   NaN
13591   NaN
13776   NaN
13810   NaN
13839   NaN
Name: INCOME_TAX, Length: 131, dtype: float64
217     NaN
234     NaN
260     NaN
290     NaN
329     NaN
         ..
13661   NaN
13694   NaN
13720   NaN
13794   NaN
13955   NaN
Name: NOPERATE_EXP, Length: 148, dtype: float64
316     NaN
564     NaN
2238    NaN
4215    NaN
4227    NaN
         ..
12056   NaN
12099   NaN
12180   NaN
13076   NaN
13160   NaN
Name: AP, Length: 157, dtype: float64
326     NaN
709     NaN
969     NaN
1144    NaN
2238    NaN
         ..
12658   NaN
12907   NaN
13410   NaN
13534   NaN
13611   NaN
Name: AR, Length: 174, dtype: float64
71      NaN
308     NaN
338     NaN
457     NaN
546     NaN
         ..
13677   NaN
13843   NaN
13848   NaN
13859   NaN
13944   NaN
Name: C_OUTF_FR_FINAN_A, Length: 191, dtype: float64
77      NaN
102     NaN
160     NaN
277     NaN
316     NaN
         ..
13792   NaN
13828   NaN
13885   NaN
13917   NaN
13928   NaN
Name: ADVANCE_RECEIPTS, Length: 211, dtype: float64
39      NaN
71      NaN
172     NaN
183     NaN
185     NaN
         ..
13754   NaN
13843   NaN
13848   NaN
13859   NaN
13944   NaN
Name: C_PAID_DIV_PROF_INT, Length: 348, dtype: float64
13      NaN
20      NaN
62      NaN
152     NaN
199     NaN
         ..
13743   NaN
13755   NaN
13782   NaN
13860   NaN
13944   NaN
Name: BASIC_EPS, Length: 369, dtype: float64
21      NaN
77      NaN
116     NaN
172     NaN
177     NaN
         ..
13727   NaN
13734   NaN
13776   NaN
13810   NaN
13839   NaN
Name: DEFER_TAX_ASSETS, Length: 380, dtype: float64
51      NaN
58      NaN
71      NaN
78      NaN
79      NaN
         ..
13743   NaN
13746   NaN
13806   NaN
13841   NaN
13939   NaN
Name: C_INF_FR_INVEST_A, Length: 427, dtype: float64
118     NaN
2408    NaN
2640    NaN
2902    NaN
3262    NaN
         ..
13929   NaN
13939   NaN
13940   NaN
13944   NaN
13968   NaN
Name: OTH_PAYABLE, Length: 604, dtype: float64
8       NaN
24      NaN
61      NaN
62      NaN
70      NaN
         ..
13890   NaN
13939   NaN
13940   NaN
13945   NaN
13949   NaN
Name: T_NCL, Length: 615, dtype: float64
283     NaN
1591    NaN
3289    NaN
4227    NaN
4237    NaN
         ..
13884   NaN
13913   NaN
13929   NaN
13940   NaN
13968   NaN
Name: OTH_RECEIV, Length: 667, dtype: float64
13      NaN
20      NaN
46      NaN
62      NaN
72      NaN
         ..
13782   NaN
13860   NaN
13875   NaN
13896   NaN
13944   NaN
Name: DILUTED_EPS, Length: 738, dtype: float64
1       NaN
5       NaN
6       NaN
8       NaN
29      NaN
         ..
13931   NaN
13939   NaN
13944   NaN
13949   NaN
13953   NaN
Name: C_INF_FR_FINAN_A, Length: 1085, dtype: float64
6       NaN
23      NaN
29      NaN
61      NaN
69      NaN
         ..
13906   NaN
13916   NaN
13944   NaN
13947   NaN
13955   NaN
Name: CIP, Length: 1206, dtype: float64
0       NaN
6       NaN
7       NaN
11      NaN
13      NaN
         ..
13676   NaN
13776   NaN
13869   NaN
13906   NaN
13912   NaN
Name: OTH_CA, Length: 1438, dtype: float64
23      NaN
24      NaN
39      NaN
60      NaN
69      NaN
         ..
13928   NaN
13944   NaN
13955   NaN
13957   NaN
13959   NaN
Name: NOTES_RECEIV, Length: 1469, dtype: float64
0       NaN
4       NaN
21      NaN
35      NaN
51      NaN
         ..
13923   NaN
13939   NaN
13949   NaN
13955   NaN
13958   NaN
Name: DISP_FIX_ASSETS_OTH, Length: 1592, dtype: float64
3       NaN
5       NaN
7       NaN
8       NaN
11      NaN
         ..
13929   NaN
13939   NaN
13940   NaN
13945   NaN
13949   NaN
Name: DEFER_REVENUE, Length: 2179, dtype: float64
0       NaN
1       NaN
5       NaN
14      NaN
27      NaN
         ..
13949   NaN
13953   NaN
13955   NaN
13959   NaN
13961   NaN
Name: C_PAID_FOR_DEBTS, Length: 2205, dtype: float64
4       NaN
6       NaN
7       NaN
11      NaN
13      NaN
         ..
13912   NaN
13913   NaN
13934   NaN
13939   NaN
13966   NaN
Name: INVEST_INCOME, Length: 2397, dtype: float64
1       NaN
5       NaN
6       NaN
8       NaN
14      NaN
         ..
13944   NaN
13949   NaN
13953   NaN
13955   NaN
13959   NaN
Name: C_FR_BORR, Length: 2525, dtype: float64
7       NaN
21      NaN
28      NaN
32      NaN
49      NaN
         ..
13952   NaN
13953   NaN
13958   NaN
13964   NaN
13966   NaN
Name: FOREX_EFFECTS, Length: 2736, dtype: float64

In [169]:
dtrain.info

<bound method DataFrame.info of        TICKER_SYMBOL  CASH_C_EQUIV  NOTES_RECEIV            AR    PREPAYMENT  \
0               4019  6.719939e+08  1.643520e+08  3.451945e+08  1.039522e+07
1               8166  1.010981e+09  2.155752e+09  2.887470e+08  1.075202e+08
2              11737  1.502023e+09  2.688988e+07  9.517806e+08  4.157376e+07
3              16479  9.966031e+08  3.686740e+05  2.824134e+08  2.741431e+07
4              16842  5.763404e+07  8.990000e+06  5.941825e+07  3.603420e+07
...              ...           ...           ...           ...           ...
13964        4990942  2.576919e+08  3.315863e+08  6.357174e+08  3.247564e+07
13965        4992204  5.346339e+07  5.015221e+07  1.062665e+08  3.001468e+06
13966        4992858  2.440501e+08  3.076474e+05  8.106961e+07  3.484379e+06
13967        4993201  1.383177e+08  2.065400e+06  2.356441e+08  2.378197e+07
13968        4998808  1.636861e+09  1.315565e+06  6.862857e+08  5.058011e+07

         OTH_RECEIV   INVENTORIES        OTH_CA          T_CA  \
0      3.584941e+06  9.372176e+07  0.000000e+00  1.291554e+09
1      8.562676e+07  1.049809e+09  1.080342e+07  4.709240e+09
2      3.751924e+07  6.611381e+08  3.919438e+08  3.619333e+09
3      6.724947e+07  3.400061e+08  8.145214e+08  2.554056e+09
4      7.755849e+05  6.985958e+07  4.721015e+05  2.331838e+08
...             ...           ...           ...           ...
13964  1.649982e+07  5.204736e+08  1.828237e+08  1.977268e+09
13965  1.910677e+06  6.922770e+07  1.312207e+06  2.853342e+08
13966  4.939396e+06  9.927149e+07  5.539442e+06  4.502721e+08
13967  1.080586e+07  3.880520e+08  2.597709e+07  8.246441e+08
13968  3.033362e+03  1.247265e+09  4.129781e+07  3.666948e+09

       AVAIL_FOR_SALE_FA  ...          COGS      N_INCOME  BIZ_TAX_SURCHG  \
0           2.188199e+08  ...  2.935500e+08  1.054685e+08      1505596.10
1           2.188199e+08  ...  3.498736e+09  3.626590e+08     28213513.69
2           1.500000e+06  ...  7.883673e+08  3.479212e+08      8298888.47
3           2.188199e+08  ...  1.743231e+09  1.043842e+08     11585500.32
4           2.188199e+08  ...  2.986392e+08  5.190705e+07      1621817.64
...                  ...  ...           ...           ...             ...
13964       1.120914e+06  ...  1.391684e+09  1.724604e+08     19976636.83
13965       2.188199e+08  ...  3.997593e+08  6.729722e+07      4930086.99
13966       2.188199e+08  ...  2.377352e+08  6.933519e+06      2920643.92
13967       2.188199e+08  ...  1.227280e+09  9.218567e+07     18134817.61
13968       4.905596e+07  ...  1.081966e+09  6.794989e+07     29732753.24

       NOPERATE_EXP  GOING_CONCERN_NI  COMPR_INC_ATTR_M_S   INCOME_TAX  \
0         224194.93      3.555384e+08        3.000168e+07  19509143.39
1        1071702.74      3.555384e+08        3.000168e+07  52563706.01
2         633458.95      3.555384e+08        2.172267e+07  36404446.16
3        1727998.62      3.555384e+08        3.681052e+04  17533501.14
4         499429.33      3.555384e+08        9.192152e+05   8519689.96
...             ...               ...                 ...          ...
13964   12343645.55      1.724604e+08        1.986097e+07  43497296.63
13965    6463772.11      6.729722e+07        3.000168e+07   9266856.60
13966     111091.53      6.933519e+06        1.889693e+06    898725.15
13967    4526795.07      9.218567e+07       -7.181958e+06  31889179.48
13968     901275.67      6.794989e+07       -5.187878e+06  13703182.05

       NOPERATE_INCOME  MINORITY_GAIN        T_COGS
0         1.678165e+07   3.058611e+07  3.885748e+08
1         2.248073e+07   3.058611e+07  4.930772e+09
2         6.036583e+07   2.172267e+07  1.384902e+09
3         1.811388e+07   3.681052e+04  2.153059e+09
4         4.847048e+06   9.192152e+05  3.384751e+08
...                ...            ...           ...
13964     3.451684e+06   1.986097e+07  1.634816e+09
13965     3.578400e+00   3.058611e+07  5.006001e+08
13966     3.232142e+04   1.889693e+06  3.113814e+08
13967     1.062773e+05  -7.181958e+06  1.650710e+09
13968     1.039995e+05  -5.190868e+06  1.648540e+09

[13969 rows x 95 columns]>

In [175]:
dtrain.to_csv("./dtrain.csv", encoding="utf8")
dtarget.to_csv("./dtarget.csv", encoding="utf8")

--- 
## 插入因子数据

In [171]:
ramdonForest_end_Data = dtrain
ramdonForest_end_Data["AP_TC"] = ramdonForest_end_Data["AP"] / ramdonForest_end_Data["AP"]
ramdonForest_end_Data["OR_TC"] = ramdonForest_end_Data["OTH_RECEIV"] / ramdonForest_end_Data["T_CA"]
ramdonForest_end_Data["IN_TC"] = ramdonForest_end_Data["INVENTORIES"] / ramdonForest_end_Data["T_CA"]
ramdonForest_end_Data["NI_NI"] = ramdonForest_end_Data["NOPERATE_INCOME"] / ramdonForest_end_Data["N_INCOME"]

In [173]:
from sklearn.model_selection import train_test_split
# 划分训练集和测试集`
X_train, X_test, y_train, y_test = train_test_split(ramdonForest_end_Data, dtarget, test_size=0.3, random_state=0)

In [174]:
# 贝叶斯优化调参
def modelfit(learning_rate, n_estimators, max_depth, min_child_weight, gamma, subsample, colsample_bytree,
             Reg_lambda, Reg_alpha):
    xgb1 = xgb.XGBClassifier(objective='binary:logistic', nthread=2,
                             n_estimators=int(n_estimators),
                             learning_rate=float(learning_rate),
                             max_depth=int(max_depth), min_child_weight=int(min_child_weight),
                             gamma=float(gamma), subsample=float(subsample),
                             colsample_bytree=float(colsample_bytree),
                             Reg_lambda=float(Reg_lambda), Reg_alpha=float(Reg_alpha),
                             scale_pos_weight=1, seed=10, ).fit(X_train, pd.DataFrame(y_train)).score(X_test, y_test)
    return xgb1


# 参数因子池
pool = {
    'learning_rate': (0.0001, 0.9999),
    'n_estimators': (400, 800),
    'max_depth': (1, 20),  # 树模型深度
    'min_child_weight': (1, 5),
    'gamma': (0.1, 0.7),
    'subsample': (0.6, 0.9),
    'colsample_bytree': (0.6, 0.9),
    'Reg_lambda': (0.001, 3),
    'Reg_alpha': (0.001, 2)

}
# 定义贝叶斯调参模型
from bayes_opt import BayesianOptimization as bayes

optimizer = bayes(f=modelfit,
                  pbounds=pool,
                  verbose=2,
                  random_state=1,
                  )

ModuleNotFoundError: No module named 'bayes_opt'

In [ ]:
# 调参并输出最优因子
optimizer.maximize(
    init_points=5,
    n_iter=25,
)
print(optimizer.max)

In [ ]:
# xgboost模型训练
xgb1 = xgb.XGBClassifier(n_estimators=545, learning_rate=0.0001,
                         max_depth=1, min_child_weight=5, gamma=0.1,
                         subsample=0.6, colsample_bytree=0.9,
                         objective='binary:logistic', nthread=2,
                         scale_pos_weight=1, seed=10, Reg_lambda=3,
                         Reg_alpha=0.001)
xgb1.fit(X_train, y_train)

y_test_pre = xgb1.predict(X_test)
y_test_true = np.array(y_test)
print("the xgboost model Accuracy : %.4g" % metrics.accuracy_score(y_pred=y_test_pre, y_true=y_test_true))

In [ ]:
# 特征重要性排名
xgb_predictors = [i for i in train_X.columns]
xgb_feat_imp = pd.Series(xgb1.feature_importances_, xgb_predictors).sort_values(ascending=False)
xgb_feat_imp.plot(kind='bar', title='Feature Importance')
plt.ylabel('Feature Importance Score')
plt.show()
print(xgb_feat_imp)

In [ ]:
# 具体的模型得分报告
from sklearn.metrics import classification_report, roc_auc_score

print(classification_report(y_test_true, y_test_pre))
print("auc值为:", roc_auc_score(y_test_true, y_test_pre))

# ROC曲线绘制
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

fpr1, tpr1, threshold1 = roc_curve(y_test_true, y_test_pre)
plt.plot(fpr1, tpr1, color='r')
plt.plot([0, 1], [0, 1], color='blue', linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.0])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('XGBClassifier ROC Curve')